[package]
name = "guessing_game_using_rust"
version = "0.1.0"
edition = "2021"
author = ["Chandrashekhar Koteakr <shekhar.kotekar@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
colored = "2.0.0"